name: build-test-publish

on:
  push:
    branches:
      - master

  release:
    types: [created]

jobs:
  build-rpi4:
    runs-on: ubuntu-latest
    container:
      image: mitchallen/pi-cross-compile
    env:
      AR: /pitools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar
      CC: /pitools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
      CFLAGS_EXTRA: '-D_BSD_SOURCE'
    steps:
    - uses: actions/checkout@v2
    - run: make -C devicetree/c-code clean all -e MACHINE=armv7l -e LIB_RESULT_DIR=builded
    - uses: actions/upload-artifact@master
      with:
        name: bin_rpi4
        path: devicetree/c-code/builded
  build-jetson-nano:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  build-linux-pc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C devicetree/c-code clean all -e LIB_RESULT_DIR=builded
    - uses: actions/upload-artifact@master
      with:
        name: bin_linux_pc
        path: devicetree/c-code/builded
  build-win10-pc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  test-rpi4:
    runs-on: ubuntu-latest
    needs: [build-rpi4]
    steps:
    - uses: actions/checkout@v2

  publish-pypi:
    runs-on: ubuntu-latest
    needs:
      - build-rpi4
      - build-jetson-nano
      - build-linux-pc
      - build-win10-pc
    steps:
    - uses: actions/checkout@v2
    - run: rm -rfv devicetree/libs
    - uses: actions/download-artifact@master
      with:
        name: bin_rpi4
        path: devicetree/libs
    - run: find . -type f
    - run: ls -al devicetree/libs/armv7l
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: '${{ secrets.PYPI_USERNAME }}'
        TWINE_PASSWORD: '${{ secrets.PYPI_PASSWORD }}'
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
