name: build-test-publish

on:
  push:
    branches:
      - master
  release:
    types: 
      - created

jobs:
  build-rpi4:
    runs-on: ubuntu-latest
    container:
      image: mitchallen/pi-cross-compile
    env:
      AR: /pitools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar
      CC: /pitools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
      CFLAGS_EXTRA: '-D_BSD_SOURCE'
    steps:
    - uses: actions/checkout@v2
    - run: make -C devicetree/c-code clean all -e MACHINE=armv7l -e LIB_RESULT_DIR=builded
    - uses: actions/upload-artifact@master
      with:
        name: bin_rpi4
        path: devicetree/c-code/builded
  build-jetson-nano:
    runs-on: ubuntu-latest
    container:
      image: kv76/cross_compile_jetson_nano:latest
    env:
      CC: /install/bin/aarch64-unknown-linux-gnu-gcc
      AR: /install/bin/aarch64-unknown-linux-gnu-ar
      CFLAGS_EXTRA: '-D_BSD_SOURCE'
    steps:
    - uses: actions/checkout@v2
    - run: make -C devicetree/c-code clean all -e MACHINE=aarch64 -e LIB_RESULT_DIR=builded
    - uses: actions/upload-artifact@master
      with:
        name: bin_jetson_nano
        path: devicetree/c-code/builded
  build-linux-pc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C devicetree/c-code clean all -e LIB_RESULT_DIR=builded
    - uses: actions/upload-artifact@master
      with:
        name: bin_linux_pc
        path: devicetree/c-code/builded

  test-unittesting:
    runs-on: ubuntu-latest
    needs:
      - build-rpi4
      - build-jetson-nano
      - build-linux-pc
    steps:
    - uses: actions/checkout@v2


  publish-pypi:
    runs-on: ubuntu-latest
    if:   github.event_name == 'release' && github.event.action == 'created'
    needs:
      - test-unittesting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: bin_rpi4
        path: devicetree/libs
    - uses: actions/download-artifact@master
      with:
        name: bin_linux_pc
        path: devicetree/libs
    - uses: actions/download-artifact@master
      with:
        name: bin_jetson_nano
        path: devicetree/libs
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: '${{ secrets.PYPI_USERNAME }}'
        TWINE_PASSWORD: '${{ secrets.PYPI_PASSWORD }}'
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  test-on-rpi4:
    runs-on: 
      - self-hosted
      - linux
      - rpi4
      - hw_mlx90641
      - hw_i2c_devicetree
    needs:
      - test-unittesting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: bin_rpi4
        path: mlx90641/libs
  test-on-jetson-nano:
    runs-on: 
      - self-hosted
      - linux
      - jetson-nano
      - hw_mlx90641
      - hw_i2c_devicetree
    needs:
      - test-unittesting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: bin_jetson_nano
        path: mlx90641/libs
  test-on-linux-pc:
    runs-on: 
      - self-hosted
      - linux
      - ubuntu
      - hw_mlx90641
      - hw_i2c_devicetree
    needs:
      - test-unittesting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: bin_linux_pc
        path: mlx90641/libs
  test-on-win10-pc:
    runs-on: 
      - self-hosted
      - windows
      - win10
      - mingw
      - hw_mlx90641
      - hw_i2c_devicetree
    needs:
      - test-unittesting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: bin_win10_pc
        path: mlx90641/libs
