name: show-report

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test-on-hardware:
    runs-on: 
      - self-hosted
      - linux
      - jetson-nano
      - hw_mlx90641
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: test-on-hardware-jetson-nano
        workflow_conclusion: success
    - run: ls -al public
