name: test-on-hardware-jetson-nano

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test-on-hardware:
    runs-on: 
      - self-hosted
      - linux
      - jetson-nano
      - hw_mlx90641
    steps:
    - uses: actions/checkout@v2
    - name: Create virtual env and run tests
      run: |
         virtualenv --version
         virtualenv venv
         source venv/bin/activate
         python --version
         pip --version
         pip install --no-input mlx90641-driver-devicetree --upgrade
         pip install --no-input pytest pytest-ordering pytest-html pytest-metadata
         python -m pytest -v tests/app_testing -p no:cacheprovider --html=public/app-tests-jetson-nano-report.html --self-contained-html --metadata homepage https://github.com/melexis-fir/mlx90641-driver-devicetree-py --metadata device_tree /dev/i2c-1 --metadata host_hardware 'Jetson Nano'
    - uses: actions/upload-artifact@master
      with:
        name: test_report
        path: public
